"""Initial schema: provenance, canonical documents, fact store, audit log, model calls.

Autogenerated from patsquire_plr.db.models, then extended by hand with the pgvector
extension and the append-only triggers (marked HAND-WRITTEN below).

Revision ID: 0001
Revises: (none)
Create Date: 2026-09-25 10:50:18.250300
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# HAND-WRITTEN: frozen copy of patsquire_plr.db.models.APPEND_ONLY_TABLES at this revision.
# A test asserts the live database protects exactly the tables the models declare.
APPEND_ONLY_TABLES = (
    "raw_record",
    "quarantined_record",
    "patent_document",
    "document_party",
    "document_priority",
    "document_classification",
    "document_citation",
    "document_forward_citation",
    "fact_computation",
    "fact",
    "audit_event",
    "llm_call",
    "llm_cache",
)


def upgrade() -> None:
    # HAND-WRITTEN: embeddings (Phase 6) need pgvector; fail here if the server lacks it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("template_version", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_snapshot_sha256", sa.String(length=64), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "status IN ('running', 'complete', 'failed', 'not_publishable')",
            name=op.f("ck_analysis_run_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_run")),
    )
    op.create_table(
        "audit_event",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("step", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "hash ~ '^[0-9a-f]{64}$' AND prev_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_audit_event_hashes"),
        ),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_audit_event")),
        sa.UniqueConstraint("hash", name=op.f("uq_audit_event_hash")),
    )
    op.create_table(
        "ingest_batch",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("adapter_version", sa.Text(), nullable=False),
        sa.Column("query_id", sa.Text(), nullable=True),
        sa.Column("query_text", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reported_count", sa.Integer(), nullable=True),
        sa.Column("stored_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "status IN ('running', 'complete', 'failed')", name=op.f("ck_ingest_batch_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_batch")),
    )
    op.create_table(
        "llm_cache",
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("backend", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("operation", sa.Text(), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("cache_key", name=op.f("pk_llm_cache")),
    )
    op.create_table(
        "llm_call",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("backend", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("model_version_reported", sa.Text(), nullable=True),
        sa.Column("operation", sa.Text(), nullable=False),
        sa.Column("prompt_id", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("cost_estimate_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_call")),
    )
    op.create_table(
        "fact",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("metric_id", sa.Text(), nullable=False),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dimensions_key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("definition_options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("query_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_set_sha256", sa.String(length=64), nullable=False),
        sa.Column("implementations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_run.id"], name=op.f("fk_fact_run_id_analysis_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact")),
        sa.UniqueConstraint(
            "run_id", "metric_id", "dimensions_key", name="uq_fact_run_id_metric_id_dimensions_key"
        ),
    )
    op.create_table(
        "fact_computation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("metric_id", sa.Text(), nullable=False),
        sa.Column("dimensions_key", sa.String(length=64), nullable=False),
        sa.Column("implementation", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_set_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_run.id"], name=op.f("fk_fact_computation_run_id_analysis_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_computation")),
    )
    op.create_table(
        "raw_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("source_record_key", sa.Text(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_raw_record_sha256_hex")),
        sa.CheckConstraint("byte_size >= 0", name=op.f("ck_raw_record_byte_size_non_negative")),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["ingest_batch.id"], name=op.f("fk_raw_record_batch_id_ingest_batch")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_record")),
        sa.UniqueConstraint(
            "batch_id", "source_record_key", name="uq_raw_record_batch_id_source_record_key"
        ),
    )
    op.create_table(
        "patent_document",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_record_id", sa.UUID(), nullable=False),
        sa.Column("raw_pointer", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("publication_country", sa.String(length=2), nullable=False),
        sa.Column("publication_number", sa.Text(), nullable=False),
        sa.Column("publication_kind", sa.Text(), nullable=True),
        sa.Column("publication_number_raw", sa.Text(), nullable=False),
        sa.Column("application_number_raw", sa.Text(), nullable=True),
        sa.Column("family_id_simple", sa.Text(), nullable=True),
        sa.Column("family_id_extended", sa.Text(), nullable=True),
        sa.Column("earliest_priority_date", sa.Date(), nullable=True),
        sa.Column("filing_date", sa.Date(), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("grant_date", sa.Date(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("claims", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=2), nullable=True),
        sa.Column("legal_status_category", sa.Text(), nullable=True),
        sa.Column("legal_status_raw", sa.Text(), nullable=True),
        sa.Column("legal_status_as_of", sa.Date(), nullable=True),
        sa.Column("forward_citations_as_of", sa.Date(), nullable=True),
        sa.Column("missing", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(missing) = 'object'", name=op.f("ck_patent_document_missing_is_object")
        ),
        sa.CheckConstraint(
            "legal_status_category IS NULL OR legal_status_category IN ('pending', 'granted', 'lapsed', 'expired', 'withdrawn', 'refused', 'revoked', 'other')",
            name=op.f("ck_patent_document_legal_status_category"),
        ),
        sa.CheckConstraint(
            "publication_country ~ '^[A-Z]{2}$'",
            name=op.f("ck_patent_document_publication_country"),
        ),
        sa.CheckConstraint(
            "(legal_status_category IS NULL) = (legal_status_raw IS NULL) AND (legal_status_category IS NULL) = (legal_status_as_of IS NULL)",
            name=op.f("ck_patent_document_legal_status_complete"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_record.id"],
            name=op.f("fk_patent_document_raw_record_id_raw_record"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patent_document")),
    )
    op.create_index(
        "ix_patent_document_family_id_extended",
        "patent_document",
        ["family_id_extended"],
        unique=False,
    )
    op.create_index(
        "ix_patent_document_family_id_simple", "patent_document", ["family_id_simple"], unique=False
    )
    op.create_index(
        "ix_patent_document_publication",
        "patent_document",
        ["publication_country", "publication_number", "publication_kind"],
        unique=False,
    )
    op.create_table(
        "quarantined_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_record_id", sa.UUID(), nullable=False),
        sa.Column("raw_pointer", sa.Text(), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_record.id"],
            name=op.f("fk_quarantined_record_raw_record_id_raw_record"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quarantined_record")),
    )
    op.create_table(
        "document_citation",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("publication_number", sa.Text(), nullable=True),
        sa.Column("publication_number_raw", sa.Text(), nullable=True),
        sa.Column("npl_text", sa.Text(), nullable=True),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "(kind = 'patent' AND publication_number IS NOT NULL AND npl_text IS NULL) OR (kind = 'npl' AND npl_text IS NOT NULL AND publication_number IS NULL)",
            name=op.f("ck_document_citation_shape"),
        ),
        sa.CheckConstraint("kind IN ('patent', 'npl')", name=op.f("ck_document_citation_kind")),
        sa.CheckConstraint(
            "origin IN ('examiner', 'applicant', 'third_party', 'unknown')",
            name=op.f("ck_document_citation_origin"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["patent_document.id"],
            name=op.f("fk_document_citation_document_id_patent_document"),
        ),
        sa.PrimaryKeyConstraint("document_id", "ordinal", name=op.f("pk_document_citation")),
    )
    op.create_table(
        "document_classification",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("scheme", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("code_raw", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "scheme IN ('cpc', 'ipc')", name=op.f("ck_document_classification_scheme")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["patent_document.id"],
            name=op.f("fk_document_classification_document_id_patent_document"),
        ),
        sa.PrimaryKeyConstraint(
            "document_id", "scheme", "code", name=op.f("pk_document_classification")
        ),
    )
    op.create_table(
        "document_forward_citation",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("citing_publication_number", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["patent_document.id"],
            name=op.f("fk_document_forward_citation_document_id_patent_document"),
        ),
        sa.PrimaryKeyConstraint(
            "document_id", "citing_publication_number", name=op.f("pk_document_forward_citation")
        ),
    )
    op.create_table(
        "document_party",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("name_raw", sa.Text(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("country_missing", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "role IN ('applicant', 'inventor')", name=op.f("ck_document_party_role")
        ),
        sa.CheckConstraint(
            "(country IS NULL) <> (country_missing IS NULL)",
            name=op.f("ck_document_party_country_or_reason"),
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_document_party_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["patent_document.id"],
            name=op.f("fk_document_party_document_id_patent_document"),
        ),
        sa.PrimaryKeyConstraint("document_id", "role", "sequence", name=op.f("pk_document_party")),
    )
    op.create_table(
        "document_priority",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("number_raw", sa.Text(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("priority_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["patent_document.id"],
            name=op.f("fk_document_priority_document_id_patent_document"),
        ),
        sa.PrimaryKeyConstraint("document_id", "ordinal", name=op.f("pk_document_priority")),
    )
    # ### end Alembic commands ###

    # HAND-WRITTEN: append-only tables reject UPDATE and DELETE (provenance, audit, Layer 8).
    op.execute(
        """
        CREATE FUNCTION plr_forbid_modification() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'table % is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$
        """
    )
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION plr_forbid_modification()"
        )
        # Row triggers do not fire on TRUNCATE, so block it with a statement trigger.
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION plr_forbid_modification()"
        )


def downgrade() -> None:
    # HAND-WRITTEN: remove the append-only protection first.
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS plr_forbid_modification()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_priority")
    op.drop_table("document_party")
    op.drop_table("document_forward_citation")
    op.drop_table("document_classification")
    op.drop_table("document_citation")
    op.drop_table("quarantined_record")
    op.drop_index("ix_patent_document_publication", table_name="patent_document")
    op.drop_index("ix_patent_document_family_id_simple", table_name="patent_document")
    op.drop_index("ix_patent_document_family_id_extended", table_name="patent_document")
    op.drop_table("patent_document")
    op.drop_table("raw_record")
    op.drop_table("fact_computation")
    op.drop_table("fact")
    op.drop_table("llm_call")
    op.drop_table("llm_cache")
    op.drop_table("ingest_batch")
    op.drop_table("audit_event")
    op.drop_table("analysis_run")
    # ### end Alembic commands ###
