"""Landscapes (Phase 5): classification scheme files, scope, taxonomy versions, approvals,
query sets and counts, discovery runs, recall checks. Autogenerated, plus append-only
triggers (HAND-WRITTEN below) on all nine tables.

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-26 10:48:20.407456
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = (
    "classification_scheme",
    "landscape",
    "taxonomy_version",
    "approval",
    "query_set",
    "search_query",
    "query_count",
    "discovery_run",
    "recall_check",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("subject_type", sa.Text(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("decided_by", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "decision IN ('approved', 'rejected')", name=op.f("ck_approval_decision")
        ),
        sa.CheckConstraint("mode IN ('human', 'automatic')", name=op.f("ck_approval_mode")),
        sa.CheckConstraint(
            "subject_type IN ('taxonomy_version', 'query_set')",
            name=op.f("ck_approval_subject_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval")),
    )
    op.create_table(
        "classification_scheme",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("scheme", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("entry_count", sa.Integer(), nullable=False),
        sa.CheckConstraint("scheme IN ('cpc')", name=op.f("ck_classification_scheme_scheme")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_scheme")),
        sa.UniqueConstraint("scheme", "version", name="scheme_version"),
    )
    op.create_table(
        "landscape",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scope_sha256", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_landscape")),
    )
    op.create_table(
        "taxonomy_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("landscape_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("classification_scheme_id", sa.UUID(), nullable=False),
        sa.Column("llm_cache_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "origin IN ('llm_draft', 'user_edit')", name=op.f("ck_taxonomy_version_origin")
        ),
        sa.ForeignKeyConstraint(
            ["classification_scheme_id"],
            ["classification_scheme.id"],
            name=op.f("fk_taxonomy_version_classification_scheme_id_classification_scheme"),
        ),
        sa.ForeignKeyConstraint(
            ["landscape_id"],
            ["landscape.id"],
            name=op.f("fk_taxonomy_version_landscape_id_landscape"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["taxonomy_version.id"],
            name=op.f("fk_taxonomy_version_parent_id_taxonomy_version"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_version")),
        sa.UniqueConstraint("landscape_id", "version", name="landscape_version"),
    )
    op.create_table(
        "query_set",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("taxonomy_version_id", sa.UUID(), nullable=False),
        sa.Column("generator_version", sa.Text(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["taxonomy_version_id"],
            ["taxonomy_version.id"],
            name=op.f("fk_query_set_taxonomy_version_id_taxonomy_version"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_query_set")),
    )
    op.create_table(
        "discovery_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("landscape_id", sa.UUID(), nullable=False),
        sa.Column("query_set_id", sa.UUID(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hops", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("batch_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["landscape_id"], ["landscape.id"], name=op.f("fk_discovery_run_landscape_id_landscape")
        ),
        sa.ForeignKeyConstraint(
            ["query_set_id"], ["query_set.id"], name=op.f("fk_discovery_run_query_set_id_query_set")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovery_run")),
    )
    op.create_table(
        "recall_check",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("query_set_id", sa.UUID(), nullable=False),
        sa.Column("universe", sa.Text(), nullable=False),
        sa.Column("known", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("found", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_set_id"], ["query_set.id"], name=op.f("fk_recall_check_query_set_id_query_set")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recall_check")),
    )
    op.create_table(
        "search_query",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("query_set_id", sa.UUID(), nullable=False),
        sa.Column("segment_id", sa.Text(), nullable=False),
        sa.Column("part", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("logical_query", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "part IN ('keywords', 'cpc', 'combined')", name=op.f("ck_search_query_part")
        ),
        sa.ForeignKeyConstraint(
            ["query_set_id"], ["query_set.id"], name=op.f("fk_search_query_query_set_id_query_set")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_query")),
        sa.UniqueConstraint("query_set_id", "segment_id", "part", "provider", name="query_key"),
    )
    op.create_table(
        "query_count",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("search_query_id", sa.UUID(), nullable=False),
        sa.Column("universe", sa.Text(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("count_is_lower_bound", sa.Boolean(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["search_query_id"],
            ["search_query.id"],
            name=op.f("fk_query_count_search_query_id_search_query"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_query_count")),
    )
    # ### end Alembic commands ###

    # HAND-WRITTEN: every change is a new row; history is never rewritten.
    for table in TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION plr_forbid_modification()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION plr_forbid_modification()"
        )


def downgrade() -> None:
    for table in TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("query_count")
    op.drop_table("search_query")
    op.drop_table("recall_check")
    op.drop_table("discovery_run")
    op.drop_table("query_set")
    op.drop_table("taxonomy_version")
    op.drop_table("landscape")
    op.drop_table("classification_scheme")
    op.drop_table("approval")
    # ### end Alembic commands ###
