"""Relevance and segment classification (Phase 6): runs, family texts, embeddings
(pgvector), decisions, label exports, gold labels and evaluations. Autogenerated, plus
append-only triggers (HAND-WRITTEN below) on all eight tables.

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-26 14:40:32.302228
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = (
    "classification_run",
    "family_text",
    "text_embedding",
    "relevance_decision",
    "segment_decision",
    "label_export",
    "gold_label",
    "evaluation",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "text_embedding",
        sa.Column("backend", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column("dims", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("backend", "model", "text_sha256", name=op.f("pk_text_embedding")),
    )
    op.create_table(
        "classification_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("query_set_id", sa.UUID(), nullable=False),
        sa.Column("taxonomy_version_id", sa.UUID(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["dataset.id"], name=op.f("fk_classification_run_dataset_id_dataset")
        ),
        sa.ForeignKeyConstraint(
            ["query_set_id"],
            ["query_set.id"],
            name=op.f("fk_classification_run_query_set_id_query_set"),
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_version_id"],
            ["taxonomy_version.id"],
            name=op.f("fk_classification_run_taxonomy_version_id_taxonomy_version"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_run")),
    )
    op.create_table(
        "evaluation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("publishable", sa.Boolean(), nullable=False),
        sa.Column("problems", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["classification_run.id"],
            name=op.f("fk_evaluation_run_id_classification_run"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation")),
    )
    op.create_table(
        "family_text",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("family_key", sa.Text(), nullable=False),
        sa.Column("publication", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("text_sha256", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["classification_run.id"],
            name=op.f("fk_family_text_run_id_classification_run"),
        ),
        sa.PrimaryKeyConstraint("run_id", "family_key", name=op.f("pk_family_text")),
    )
    op.create_table(
        "label_export",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("family_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("purpose IN ('sample', 'review')", name=op.f("ck_label_export_purpose")),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["classification_run.id"],
            name=op.f("fk_label_export_run_id_classification_run"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_label_export")),
    )
    op.create_table(
        "relevance_decision",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("family_key", sa.Text(), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("band", sa.Text(), nullable=False),
        sa.Column("judged", sa.Boolean(), nullable=False),
        sa.Column("judge", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("final", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "band IN ('high', 'middle', 'low', 'no_text')", name=op.f("ck_relevance_decision_band")
        ),
        sa.CheckConstraint(
            "final IN ('relevant', 'not_relevant', 'uncertain', 'no_text')",
            name=op.f("ck_relevance_decision_final"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["classification_run.id"],
            name=op.f("fk_relevance_decision_run_id_classification_run"),
        ),
        sa.PrimaryKeyConstraint("run_id", "family_key", name=op.f("pk_relevance_decision")),
    )
    op.create_table(
        "segment_decision",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("family_key", sa.Text(), nullable=False),
        sa.Column("segment_id", sa.Text(), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("embedding_vote", sa.Boolean(), nullable=False),
        sa.Column("judge_vote", sa.Boolean(), nullable=True),
        sa.Column("judge", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("final", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "final IN ('assigned', 'not_assigned', 'uncertain')",
            name=op.f("ck_segment_decision_final"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["classification_run.id"],
            name=op.f("fk_segment_decision_run_id_classification_run"),
        ),
        sa.PrimaryKeyConstraint(
            "run_id", "family_key", "segment_id", name=op.f("pk_segment_decision")
        ),
    )
    op.create_table(
        "gold_label",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("export_id", sa.UUID(), nullable=False),
        sa.Column("family_key", sa.Text(), nullable=False),
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("label", sa.Boolean(), nullable=False),
        sa.Column("labeller", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "task = 'relevance' OR task LIKE 'segment:%%'", name=op.f("ck_gold_label_task")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["dataset.id"], name=op.f("fk_gold_label_dataset_id_dataset")
        ),
        sa.ForeignKeyConstraint(
            ["export_id"], ["label_export.id"], name=op.f("fk_gold_label_export_id_label_export")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gold_label")),
    )
    op.create_index(
        "ix_gold_label_dataset_family", "gold_label", ["dataset_id", "family_key"], unique=False
    )
    # ### end Alembic commands ###

    # HAND-WRITTEN: decisions and labels are never changed; a new run or label is a new row.
    for table in TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION plr_forbid_modification()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION plr_forbid_modification()"
        )


def downgrade() -> None:
    for table in TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_gold_label_dataset_family", table_name="gold_label")
    op.drop_table("gold_label")
    op.drop_table("segment_decision")
    op.drop_table("relevance_decision")
    op.drop_table("label_export")
    op.drop_table("family_text")
    op.drop_table("evaluation")
    op.drop_table("classification_run")
    op.drop_table("text_embedding")
    # ### end Alembic commands ###
